MovieApp/Models/Movie.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieAPI.Models
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Director { get; set; }
        public int YearReleased { get; set; }



    }
}

MovieApp/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MovieApp/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using MovieAPI.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;

namespace MovieApp.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public List<Movie> Movies { get; set; }
        

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public async Task OnGet()
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync("https://localhost:44368/api/Movies").Result.Content.ReadAsStringAsync();
                Movies = JsonConvert.DeserializeObject<List<Movie>>(response);
            }

        }

        public async Task OnPostFindMovieByTitle(string title)
        {
            using (var client = new HttpClient())
            {
                var response = await client.GetAsync("https://localhost:44368/api/Movies").Result.Content.ReadAsStringAsync();
                Movies = JsonConvert.DeserializeObject<List<Movie>>(response).Where(x => x.Title == title).ToList();
            }

            

        }

        /* public int Id { get; set; }
           public string Title { get; set; }
           public string Director { get; set; }
           public int YearReleased { get; set; } */

        public async void OnPostFindMovie(string Title, string Director, int YearReleased)
        {
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:44368/api/Movies");

                var movie = new Movie();
                movie.Director = Director;
                movie.Title = Title;
                movie.YearReleased = YearReleased;

                var json = JsonConvert.SerializeObject(movie);

                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var result = await client.PostAsync("Movies", content);
                string resContent = await result.Content.ReadAsStringAsync();
                

            }
            await OnGet();
        }

        
    }
}

MovieApp/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MovieApp.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MovieApp/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<style>
    body {
        background-color: slategrey;
    }
</style>


@{
    <h1 style="text-align:center;"> Movie Collection  </h1>

    <form method="post" class="form-vertical" style="text-align:center;">
        <input type="text" name="Title" placeholder="Title" required/>
        <button type="submit" class="btn btn-primary" asp-page-handler="FindMovieByTitle">Search Movie</button>

    </form>

    <form method="post" class="form-vertical" style="text-align:center;">
        <input type="text" name="Title" placeholder="Title" required />
        <input type="text" name="Director" placeholder="Director" required />
        <input type="number" name="YearReleased" placeholder="Year Released" required />
        <button type="submit" class="btn btn-primary" asp-page-handler="FindMovie">Add Movie</button>
    </form>

    foreach (var m in Model.Movies)
    {
        <h3 style="text-align:center;"> @m.Title - @m.Director @m.YearReleased </h3>
    }



}

MovieApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MovieApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">MovieApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="text-align:center; color:black;" >
            &copy; 2021 - MovieApp - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>